# Generated by Django 2.2.3 on 2019-07-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_auto_20190713_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='txt',
            name='by',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='txt',
            name='bytext',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='txt',
            name='bytextwhen',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
