# Generated by Django 2.2.3 on 2019-07-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_auto_20190713_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255)),
                ('link', models.URLField()),
            ],
        ),
    ]
