# Generated by Django 2.2.3 on 2019-07-15 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_main_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txt',
            name='bytextwhen',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=255),
        ),
    ]
