# Generated by Django 2.2.3 on 2019-07-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0010_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_me',
            name='text',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
