# Generated by Django 2.2.3 on 2019-07-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0014_auto_20190716_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='about_photo')),
                ('text', models.TextField()),
            ],
        ),
    ]
