# Generated by Django 2.2.3 on 2019-07-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0019_auto_20190717_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=True, upload_to='post'),
            preserve_default=False,
        ),
    ]
