# Generated by Django 2.2.3 on 2019-07-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0028_remove_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='profil_photo'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profil_photo'),
        ),
    ]
