# Generated by Django 2.2.3 on 2019-07-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0029_auto_20190718_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='fullname',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
