# Generated by Django 2.2.3 on 2019-07-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0030_profil_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='update')),
            ],
        ),
    ]
