# Generated by Django 2.2.3 on 2019-07-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0034_auto_20190725_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='about',
            field=models.CharField(max_length=400),
        ),
    ]
