# Generated by Django 2.2.3 on 2019-07-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0035_auto_20190725_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_user',
            name='about',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
