# Generated by Django 2.2.3 on 2019-07-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0036_register_user_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_user',
            name='about',
        ),
    ]
